TimeManagement/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TimeManagement.Domain;
using TimeManagement.Models;
using TimeManagement.Domain.Services;
using TimeManagement.ViewModel;
using System.IO;
using System.Data;
using System.Data.SqlClient;
using System.Data.Objects;
using System.Data.EntityClient;
using System.Web.UI;
using Rotativa;
using Newtonsoft.Json;

namespace TimeManagement.Controllers
{
    public class ReportController : BaseController
    {
        #region Private Methdos

        private List<SelectListItem> GetLocations()
        {
            List<string> locations = this.db.Locations.OrderBy(x=>x.Name).Select(x => x.Name).ToList();

            List<SelectListItem> items = new List<SelectListItem>();
           // items.Add(new SelectListItem { Text = "", Value = "" });

            locations.ForEach(x =>
            {
                items.Add(new SelectListItem { Text = x, Value = x });
            });

            return items;
        }
        
        private List<SelectListItem> GetProjects()
        {
            List<string> Projects = this.db.Projects.OrderBy(x=>x.Name).Select(x => x.Name).ToList();

            List<SelectListItem> items = new List<SelectListItem>();
        //    items.Add(new SelectListItem { Text = "", Value = "" });

            Projects.ForEach(x =>
            {
                items.Add(new SelectListItem { Text = x, Value = x });
            });

            return items;
        }

        private List<SelectListItem> GetWorkCodes()
        {
            List<string> WorkCodes = this.db.WorkCodes.OrderBy(x => x.Name).Select(x => x.Name).ToList();

            List<SelectListItem> items = new List<SelectListItem>();
           // items.Add(new SelectListItem { Text = "", Value = "" });

            WorkCodes.ForEach(x =>
            {
                items.Add(new SelectListItem { Text = x, Value = x });
            });

            return items;
        }

        private List<SelectListItem> GetEmployees()
        {
            List<string> Employees = this.db.Employees.OrderBy(x=>x.LastName).ThenBy(x=>x.FirstName).Select(x => x.LastName+","+x.FirstName).ToList();

            List<SelectListItem> items = new List<SelectListItem>();
            items.Add(new SelectListItem { Text = "Select Employee", Value = "" });

            Employees.ForEach(x =>
            {
                items.Add(new SelectListItem { Text = x, Value = x });
            });

            return items;
        }

        #endregion

        #region Public Methods

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [Authorize]
        public ActionResult TimeByDate()
        {
            ViewBag.locations = this.GetLocations();
            ViewBag.Projects = this.GetProjects();
            ViewBag.WorkCodes = this.GetWorkCodes();
            ViewBag.Employees = this.GetEmployees();
            return View();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="task"></param>
        /// <returns></returns>
        public ActionResult EmployeeActivities()
        {
            ViewBag.locations = this.GetLocations();
          
            ViewBag.Projects = this.GetProjects();
          
            return View();
        }

        public ActionResult TimeSheetManagement()
        {
            ViewBag.locations = this.GetLocations();
          
            return View();
        }

        public ActionResult GetUnCompleteTask(string fromDate, string toDate, string location)
        {
            List<Employee> tasks = null;
          
            if (string.IsNullOrEmpty(fromDate) && string.IsNullOrEmpty(toDate))
            {
                // fromDate = DateTime.Now.ToShortDateString();

                if (User.IsInRole(Constants.ROLE_ADMIN))
                    tasks = this.taskService.GetUnCompleteTasks(fromDate, toDate, location);
                else
                    tasks = this.taskService.GetUnCompleteTasks(fromDate, toDate, location);
                ViewBag.Message = "Result of " + DateTime.Now.ToShortDateString();
            }
            else
            {
                if (User.IsInRole(Constants.ROLE_ADMIN))
                    tasks = this.taskService.GetUnCompleteTasks(fromDate, toDate, location);
                else
                    tasks = this.taskService.GetUnCompleteTasks(fromDate, toDate, location);

                if (!string.IsNullOrEmpty(toDate))
                    ViewBag.Message = "Result from " + fromDate + " to " + toDate;
                else
                    ViewBag.Message = "Result of " + fromDate;
            }
            if (tasks != null)
            {
                var result = from task in tasks
                             select new
                             {
                                 EmployeeName = task.LastName + ',' + task.FirstName
                             };

                Session["Tasks"] = tasks;

                var resultData = new
                {
                    aaData = result
                };
                return Json(resultData, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(null, JsonRequestBehavior.AllowGet);
            }
        }
        [HttpGet]
        public ActionResult CategoryWiseReport()
        {
            ViewBag.Locations = taskService.getlocations();
            return View();
        }


        public ActionResult CategoryWiseReport(string fromdate, string todate,string LocationId)
        {
            ViewBag.resultcount = false;
            CategoryWiseModel objcat = new CategoryWiseModel();

            if (LocationId == null || LocationId == "")
            {
                LocationId = "0";
            }

            objcat.data = taskService.getcategorydata(Convert.ToDateTime(fromdate), Convert.ToDateTime(todate), Int16.Parse(LocationId));

            if (objcat.data.Rows.Count == 0)
            {
               ViewBag.resultcount = true;
            }
            return PartialView("~/Views/Report/_PVcategoryreport.cshtml", objcat);
        }

        public ActionResult GetEmployeeActivity(string fromDate, string toDate, string project, string location)
        {
            List<Task> tasks = null;
            if (string.IsNullOrEmpty(fromDate) && string.IsNullOrEmpty(toDate))
            {
                // fromDate = DateTime.Now.ToShortDateString();

                if (User.IsInRole(Constants.ROLE_ADMIN))
                    tasks = this.taskService.GetActivity(fromDate,toDate,project,location);
                else
                    tasks = this.taskService.GetActivity(fromDate, toDate, project,location);
                ViewBag.Message = "Result of " + DateTime.Now.ToShortDateString();
            }
            else
            {
                if (User.IsInRole(Constants.ROLE_ADMIN))
                    tasks = this.taskService.GetActivity(fromDate, toDate, project,location);
                else
                    tasks = this.taskService.GetActivity(fromDate, toDate, project,location);

                if (!string.IsNullOrEmpty(toDate))
                    ViewBag.Message = "Result from " + fromDate + " to " + toDate;
                else
                    ViewBag.Message = "Result of " + fromDate;
            }

            if (tasks != null)
            {
                var result = from task in tasks
                             select new
                              {
                                  Date = Convert.ToDateTime(task.ExecutionDate).ToString("MM/dd/yyyy"),
                                  EmployeeName = task.Employee.LastName + ',' + task.Employee.FirstName,
                                  ProjectName = task.Project.Name,
                                  Hours = task.Hours
                                  // Hours = Convert.ToDecimal(task.Hours).ToString("0.00")                        


                              };

                var rslt = from res in result
                           group res by new { res.Date, res.EmployeeName, res.ProjectName }
                               into grp
                               select new { grp.Key.Date, grp.Key.EmployeeName, grp.Key.ProjectName, Hours = Convert.ToDecimal(grp.Sum(x => (x.Hours))).ToString("0.00") };



                Session["Tasks"] = tasks;

                var resultData = new
                {
                    aaData = rslt
                };
                return Json(resultData, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(null, JsonRequestBehavior.AllowGet);
            }
        }
        [HttpGet]
        public ActionResult GetTimeByDate(string fromDate, string toDate, string userName, string location, string project, string workcode, string employee)
        {
            if (string.IsNullOrEmpty(location))
                location = null;

            List<Task> tasks = null;
            Session["Tasks"] = null;

            if (string.IsNullOrEmpty(fromDate) && string.IsNullOrEmpty(toDate))
            {
               // fromDate = DateTime.Now.ToShortDateString();

                if (User.IsInRole(Constants.ROLE_ADMIN))
                    tasks = this.taskService.GetTasks(fromDate, toDate, null, location, project, workcode, employee);
                else
                    tasks = this.taskService.GetTasks(fromDate, toDate, User.Identity.Name, location, project, workcode, employee);

                ViewBag.Message = "Result of " + DateTime.Now.ToShortDateString();
            }
            else
            {
                if (User.IsInRole(Constants.ROLE_ADMIN))
                    tasks = this.taskService.GetTasks(fromDate, toDate, null, location, project, workcode, employee);
                else

TimeManagement/Views/Report/Billing.cshtml
@model TimeManagement.ViewModel.BillingModel
<script type="text/javascript">


    function datevalidate() {
        var fromdate = $('#fromdate').val();
        var todate = $('#todate').val();

        if ((Date.parse(fromdate) > Date.parse(todate))) {
            alert("To Date should be greater than From date.");
            document.getElementById("todate").value = "";
            return false;
        }

        return true;

    }



    $(document).ready(function () {

        //Export button click event on batch list page
        $("#btnExport").click(function () {
            location.href = '@Url.Content("~/Report/ExportBillingDetails")';
        });

        $('#location').selectpicker({ noneSelectedText: 'Select Location' });

        $("#fromdate").change(function () {
            var fromdate = $('#fromdate').val();
            if (fromdate == "") {
                $('#fdate').removeClass('hidden');
                return false;
            } else if (fromdate != "") {
                $('#fdate').addClass('hidden');
                return false;
            }
            return true;

        });

        $("#todate").change(function () {
            var todate = $('#todate').val();
            if (todate == "") {
                $('#tdate').removeClass('hidden');
                return false;
            } else if (todate != "") {
                $('#tdate').addClass('hidden');
                return false;
            }
            return true;

        });


    });

    function fundate() {
        var fromdate = $('#fromdate').val();
        var todate = $('#todate').val();
        if ((fromdate == "") && (todate == "")) {
            $('#fdate').removeClass('hidden');
            $('#tdate').removeClass('hidden');
            return false;
        } else if ((fromdate != "") && (todate == "")) {
            $('#fdate').addClass('hidden');
            $('#tdate').removeClass('hidden');
            return false;
        } else if ((fromdate == "") && (todate != "")) {
            $('#fdate').removeClass('hidden');
            $('#tdate').addclass('hidden');
            return false;
        }
        if (datevalidate() == false) {
            return false;
        }
        return true;
    }

</script>
<div class="row">
    <div class="boxshade">
        <div class="boxhead">
            Billing Report
        </div>
        <div class="boxbody">
            <div class="col-lg-12 pad10 gap-bottom10" style="background-color: #F5F5F5;">
                <div class="col-lg-12 gap-bottom10">
                    @using (Html.BeginForm("Billing", "Report", FormMethod.Post, new { @class = "form-inline" }))
                    {
                        <div class="col-lg-2">
                            <div class="col-lg-12 pad0 gap-bottom5">
                                <b>From Date</b></div>
                            <div class="col-lg-12 pad0">
                                <input type="text" class="form-control datePicker required" id="fromdate" placeholder="From"
                                    name="fromDate" />
                                <div id="fdate" class="hidden">
                                    From Date Required</div>
                            </div>
                        </div>
                 
                        <div class="col-lg-2">
                            <div class="col-lg-12 pad0 gap-bottom5">
                                <b>To Date</b></div>
                            <div class="col-lg-12 pad0">
                                <input type="text" class="form-control datePicker required" id="todate" placeholder="To" name="toDate" />
                                <div id="tdate" class="hidden">
                                    To Date Required</div>
                            </div>
                        </div>
                        <div class="col-lg-2">
                            <div class="col-lg-12 pad0 gap-bottom5">
                                <b>Location</b></div>
                            <div class="col-lg-12 pad0">
                                @Html.DropDownList("locations", null,"Select Location", new { @class = "form-control", id = "location" })
                            </div>
                        </div>
                        <div class="col-lg-12 gap-top5">
                            <button type="submit" onclick="return fundate();" class="btn btn-small btn-primary pull-right">
                                Submit</button>
                        </div>
                        
                        
                    }
                </div>
                <div class="col-lg-12">
                    <span style="font-size: 12px">@ViewBag.Message</span>
                </div>
            </div>
            @if (Model != null && Model.Summary.Count > 0)
            {
                <div class="col-lg-12 gap-bottom10">
                    <table id="dataTable" class="table table-striped table-bordered" style="font-size: 12px">
                        <thead>
                            <tr>
                                <th style="background-color: #2481B7; color: #FFF">
                                    Company
                                </th>
                                <th style="background-color: #2481B7; color: #FFF">
                                    Consultant
                                </th>
                                <th style="background-color: #2481B7; color: #FFF">
                                    Work Code
                                </th>
                                <th style="background-color: #2481B7; color: #FFF">
                                    Bill Rate
                                </th>
                                <th style="background-color: #2481B7; color: #FFF">
                                    Hours
                                </th>
                                <th style="background-color: #2481B7; color: #FFF">
                                    Total
                                </th>
                            </tr>
                        </thead>
                        @{
                decimal total = 0;
                foreach (TimeManagement.Domain.WorkSummary workSummary in Model.Summary)
                {
                    total = 0;
                        
                            <tr>
                                <td style="text-align: left">@workSummary.Company
                                </td>
                                <td style="text-align: left">@workSummary.Employee
                                </td>
                                <td style="text-align: left">@workSummary.WorkCode
                                </td>
                                <td style="text-align: right">
                                    $@workSummary.BillRate
                                </td>
                                <td style="text-align: center">@workSummary.Hours
                                </td>
                                <td style="text-align: right">
                                    $@workSummary.Total
                                </td>
                            </tr>
			       
                }
                        }
                    </table>
                </div>
                <div class="col-lg-12 gap-bottom10">
                    <button type="button" class="btn btn-success export pull-right" id="btnExport">
                        Export</button>
                </div>
            }
        </div>
    </div>
</div>

TimeManagement/Views/Report/CategoryWiseReport.cshtml
@model TimeManagement.Models.CategoryWiseModel
@using System.Data;
@using System.Threading;
@{
    ViewBag.Title = "ResourceWiseTimeSheet";

}
<script type="text/javascript">

    var oTable;
    function showexport() {
        $("#exporttoCSV").show();
    }
    function datevalidate() {
        var fromdate = $('#fromdate').val();
        var todate = $('#todate').val();

        if ((Date.parse(fromdate) > Date.parse(todate))) {
            alert("To Date should be greater than From date.");
            document.getElementById("todate").value = "";
            return false;
        }

        return true;

    }

    $(document).ready(function () {
        $("#exporttoCSV").hide();
        $("#exporttoCSV").click(function () {
            var from_date = $('#fromdate').val();
            var to_date = $('#todate').val();
            var loc = $('#location').val();
            //var url = '@Url.Action("ExportToCSVCategory", "Report",new{fromdate="fd",todate="td",location="lc"})';
            //location.href = url.replace('fd', from_date).replace('td', to_date).replace('lc', loc);
            window.location.href = '../Report/ExportToCSVCategory?fromdate=' + from_date + '&todate=' + to_date + '&location=' + loc;
        });
        $("#fromdate").change(function () {
            var fromdate = $('#fromdate').val();
            if (fromdate == "") {
                $('#fdate').removeClass('hidden');
                return false;
            } else if (fromdate != "") {
                $('#fdate').addClass('hidden');
                return false;
            }
            return true;

        });
        $("#todate").change(function () {
            var todate = $('#todate').val();
            if (todate == "") {
                $('#tdate').removeClass('hidden');
                return false;
            } else if (todate != "") {
                $('#tdate').addClass('hidden');
                return false;
            }
            return true;
        });

    });

    function checkdate() {
        var fromdate = $('#fromdate').val();
        var todate = $('#todate').val();
        if ((fromdate == "") && (todate == "")) {
            $('#fdate').removeClass('hidden');
            $('#tdate').removeClass('hidden');
            $("#tablediv").html(' ');
            $("#exporttoCSV").hide();     
            return false;
        } else if ((fromdate != "") && (todate == "")) {
            $('#fdate').addClass('hidden');
            $('#tdate').removeClass('hidden');
            $("#tablediv").html(' ');
            $("#exporttoCSV").hide();    
            return false;
        } else if ((fromdate == "") && (todate != "")) {
            $('#fdate').removeClass('hidden');
            $('#tdate').addclass('hidden');
            $("#tablediv").html(' ');
            $("#exporttoCSV").hide();    
            return false;
        }
        if (datevalidate() == false) {
            $("#tablediv").html(' ');
            $("#exporttoCSV").hide();    
            return false;
        }
        else {
            $("#tablediv").html(' ');
            $("#exporttoCSV").hide();
            $.ajax({
                type: 'POST',
                url: '@Url.Content("~/Report/CategoryWiseReport")',
                data: { fromdate: $("#fromdate").val(), todate: $("#todate").val(), LocationId: $("#location").val() },
                success: function (data) {
                    $("#tablediv").html(data);
                },
                cache: false

            });

        }

    }

   
</script>
<div class="row">
    <div class="boxshade">
        <div class="boxhead">
            Category Wise Report
        </div>
        <div class="boxbody">
            <div class="col-lg-12 pad10" style="background-color: #F5F5F5;">
                <div class="col-lg-12 gap-bottom10">
                    @* @using (Html.BeginForm("CategoryWiseReport", "Report", FormMethod.Post, new { id = "category" }))
                    {
                     *@
                    <div class="col-lg-2">
                        <div class="col-lg-12 pad0 gap-bottom5">
                            <b>From Date</b>
                        </div>
                        <div class="col-lg-12 pad0">
                            <input type="text" id="fromdate" class="form-control datePicker required" placeholder="From"
                                name="fromDate" />
                            @*  @Html.TextBoxFor(m => m.fromdate, new { @class = "form-control datePicker required", placeholder = "From" })*@
                            <div id="fdate" class="hidden">
                                From Date Required
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-2">
                        <div class="col-lg-12 pad0 gap-bottom5">
                            <b>To Date</b>
                        </div>
                        <div class="col-lg-12 pad0">
                            @* @Html.TextBoxFor(m => m.todate, new { @class = "form-control datePicker required", placeholder = "To" })*@
                            <input type="text" id="todate" class="form-control datePicker required" placeholder="To"
                                name="toDate" />
                            <div id="tdate" class="hidden">
                                To Date Required
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-2">
                        <div class="col-lg-12 pad0 gap-bottom5">
                            <b>Location</b></div>
                            @{
                                List<SelectListItem> list = ViewBag.Locations;
                               }

                        <div class="col-lg-12 pad0">
                            @Html.DropDownList("locations", list, "Select Location", new { @class = "form-control", id = "location" })
                        </div>
                    </div>
                    <div class="col-lg-12 gap-top5">
                     <input type="button" class="btn btn-small btn-success pull-right gap-left5"
                            id="exporttoCSV" value="Export" />
                           
                        <input type="submit" onclick="return checkdate();" class="btn btn-small btn-primary pull-right"
                            id="getreport" value="Submit" />
                    </div>
                    @*   }*@
                </div>
            </div>
            <div class="col-lg-12 gap-bottom10" style="padding-left:0px; padding-right:0px;"id="tablediv">
                @*<table id="Categorytable" class="custom table table-striped table-bordered">
                        @if (Model.data.Rows.Count > 0)
                        {
                            <thead>
                                <tr>
                                    @for (int i = 0; i <= Model.data.Columns.Count - 1; i++)
                                    {
                                        <th class="text-center">@Model.data.Columns[i]
                                        </th>
                
                                    }
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (DataRow row in Model.data.AsEnumerable())
                                {

                                    if (row[0].ToString().Trim() != "Total")
                                    {                 
                                    <tr>
                                        @for (int i = 0; i <= row.Table.Columns.Count - 1; i++)
                                        {

                                            if (Model.data.Columns[i].ColumnName.Trim() == "Resource")
                                            {
                                            <td class="text-left">@row[i].ToString()
                                            </td>       
                                            }
                                            else if (Model.data.Columns[i].ColumnName.Trim() == "Role")
                                            {
                                            <td class="text-left">@row[i].ToString()
                                            </td>
                                            }
                                            else
                                            {
                                            <td class="text-right">@row[i].ToString()
                                            </td>  
                                            }
                                        }
                                    </tr>
                                    }
                                }
                            </tbody>
                        }
                        @if (Model.data.Rows.Count > 0)
                        {
                            <tfoot>
                                <tr>
                                    @{
                            DataRow row = (DataRow)Model.data.Rows[Model.data.Rows.Count - 1];
                            for (int j = 0; j <= Model.data.Columns.Count - 1; j++)
                            {
                                        <td class="text-right">
                                            @row[j].ToString()
                                        </td>                                 
                           
                            }                        
                                    }
                                </tr>
                            </tfoot>
                        }
                    </table>*@
            </div>
        </div>
    </div>
</div>

TimeManagement/Views/Report/_PVEmployeeDetailedActivity.cshtml
@model TimeManagement.ViewModel.ActivityWiseModel
@using System.Data;
@{
    Layout = null;
}
<script type="text/javascript">

    $(document).ready(function () {
        var variable = '@(Model.data.Rows.Count)';
        if (variable != 0) {
            showexport();
            if (oTable) {
                oTable.fnDestroy();
            }
            oTable = $('#Activitytable').dataTable({
                "iDisplayLength": 10,
                "aLengthMenu": [[10, 20, 30, 40, 50, -1], [10, 20, 30, 40, 50, "All"]],
                "bSort": true,
                "bPaginate": true,
                "bFilter": true,
                "bInfo": true,
                "bAutoWidth": false,
                "aaSorting": [[0, "asc"]]
            }).wrap("<div style='position:relative;overflow:auto;'/>");
            $("#Activitytable").find("tr:last td:eq(0)").css("font-weight", "bold");
        }
    });
 
</script>
<style>
    #Categorytable_wrapper > .row
    {
        margin-top: 10px !important;
    }
</style>
@if (Model.data.Rows.Count == 0)
{                 <div class="col-lg-12" style="background-color: #F5F5F5; padding: 10px;">
    No Records Available
    </div>
}
<table id="Activitytable" class="custom table table-striped table-bordered gap-bottom10">
    @if (Model.data.Rows.Count > 0)
    {
        <thead>
            <tr>
                @for (int i = 0; i <= Model.data.Columns.Count - 1; i++)
                {
                    <th style="background-color: #2481B7; color: #FFF; min-width: 120px;" class="text-center">@Model.data.Columns[i]
                    </th>
                
                }
            </tr>
        </thead>
        <tbody>
            @foreach (DataRow row in Model.data.AsEnumerable())
            {

                if (row[0].ToString().Trim() != "Total")
                {                 
                <tr>
                    @for (int i = 0; i <= row.Table.Columns.Count - 1; i++)
                    {

                        if (Model.data.Columns[i].ColumnName.Trim() == "Date")
                        {
                        <td class="text-left">@row[i].ToString()
                        </td>       
                        }
                        else if (Model.data.Columns[i].ColumnName.Trim() == "Role")
                        {
                        <td class="text-left">@row[i].ToString()
                        </td>
                        }
                        else
                        {
                        <td class="text-right">@row[i].ToString()
                        </td>  
                        }
                    }
                </tr>
                }
            }
        </tbody>
    }
    @if (Model.data.Rows.Count > 0)
    {
        <tfoot>
            <tr>
                @{
        DataRow row = (DataRow)Model.data.Rows[Model.data.Rows.Count - 1];
        for (int j = 0; j <= Model.data.Columns.Count - 1; j++)
        {
                    <td class="text-right">
                        @row[j].ToString()
                    </td>                                 
                           
        }                        
                }
            </tr>
        </tfoot>
    }
</table>