TimeManagement/Models/Configuration.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuration
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Percentage { get; set; }
        public Nullable<decimal> Rate { get; set; }
    }
}

TimeManagement/Models/Customer.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string CustomerType { get; set; }
        public string CustomerAddress1 { get; set; }
        public string CustomerAddress2 { get; set; }
        public string Description { get; set; }
    }
}

TimeManagement/Models/Employee.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Tasks = new HashSet<Task>();
            this.EmployeeRoles = new HashSet<EmployeeRole>();
            this.EmployeeProjects = new HashSet<EmployeeProject>();
            this.WeeklyReports = new HashSet<WeeklyReport>();
        }
    
        public int Id { get; set; }
        public int LocationId { get; set; }
        public string Prefix { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Suffix { get; set; }
        public Nullable<decimal> BillRate { get; set; }
        public string CompanyName { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string EmployeeCode { get; set; }
        public string DOB { get; set; }
        public string DOJ { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string DOR { get; set; }
        public Nullable<bool> EmailReminder { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual Login Login { get; set; }
        public virtual ICollection<EmployeeRole> EmployeeRoles { get; set; }
        public virtual ICollection<EmployeeProject> EmployeeProjects { get; set; }
        public virtual ICollection<WeeklyReport> WeeklyReports { get; set; }
    }
}

TimeManagement/Models/Location.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Employee> Employees { get; set; }
    }
}

TimeManagement/Models/Project.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.Tasks = new HashSet<Task>();
            this.EmployeeProjects = new HashSet<EmployeeProject>();
            this.WeeklyReports = new HashSet<WeeklyReport>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Number { get; set; }
        public Nullable<System.DateTime> EstStartDate { get; set; }
        public Nullable<System.DateTime> EstEndDate { get; set; }
        public Nullable<bool> IsCommon { get; set; }
        public string Customer { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string Risk { get; set; }
        public string Discount { get; set; }
        public string MarginValue { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public string Completed { get; set; }
        public bool Te { get; set; }
        public bool Tm { get; set; }
        public Nullable<int> TypeOfProject { get; set; }
    
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual ICollection<EmployeeProject> EmployeeProjects { get; set; }
        public virtual ICollection<WeeklyReport> WeeklyReports { get; set; }
    }
}

TimeManagement/Models/WorkCode.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkCode
    {
        public WorkCode()
        {
            this.Tasks = new HashSet<Task>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Number { get; set; }
        public bool Billable { get; set; }
    
        public virtual ICollection<Task> Tasks { get; set; }
    }
}

TimeManagement/Controllers/MasterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TimeManagement.Models;
using TimeManagement.ViewModel;
using System.Data;
using TimeManagement.Domain;
using System.Data.Entity.Validation;

namespace TimeManagement.Controllers
{
    public class MasterController : BaseController
    {

        #region Projects

        [HttpGet]
        public ActionResult GetProjects()
        {
            return View("Projects");
        }


        public ActionResult ResetPWD(int id)
        {
            Login existingTask = this.db.Logins.Where(x => x.Employee.Id.Equals(id)).FirstOrDefault();           
            //Login existingTask = this.db.Logins.Find(id);           

            return PartialView("_PVResetPwdForEmployees", existingTask);
        }

        [HttpPost]
        public ActionResult ResetPwdForEmployees(Login model)
        {
            //string userName = Request.Form["UserName"];           
            string userName = model.UserId;
            string password = model.Password;
            // string confirmpassword = Request.Form["confirmPassword"];


            if (this.MembershipService.ChangePassword(userName, password))
            {
                ViewBag.Msg = "Success";
              //  return View("Employees");
                return Content("UPDATE_S");
            }
            else
            {
                TempData["error"] = "The user name or password provided is incorrect.";
                return RedirectToAction("Index");
            }
        }


        public ActionResult GetProject(jQueryDataTableParamModel param)
        {

            IQueryable<Project> tasks = this.db.Projects;

            if (tasks != null)
            {
                List<ProjectModel> result = new List<ProjectModel>();

                foreach (Project task in tasks)
                {
                    ProjectModel taskModel = new ProjectModel();
                    taskModel.DT_RowId = task.Id.ToString();
                    taskModel.projectcode = task.Number;
                    taskModel.projectname = task.Name;
                    taskModel.estdstartdate = task.EstStartDate != null ? task.EstStartDate.Value.ToString("MM/dd/yyyy") : "";
                    taskModel.estdenddate = task.EstEndDate != null ? task.EstEndDate.Value.ToString("MM/dd/yyyy") : "";
                    taskModel.Customer = task.Customer;
                    taskModel.TotalAmount = task.TotalAmount.ToString();
                    taskModel.Risk = task.Risk;
                    taskModel.Discount = task.Discount;
                    taskModel.MarginValue = task.MarginValue;
                    taskModel.DiscountAmount = task.DiscountAmount != null ? task.DiscountAmount.Value.ToString("00") : "";
                    taskModel.Completed = task.Completed;
                    taskModel.Te = task.Te.ToString();
                    taskModel.Tm = task.Tm.ToString();

                    result.Add(taskModel);
                }

                var resultData = new
                {
                    aaData = result
                };
                //  ViewData["Data"] = result;
                return Json(resultData, JsonRequestBehavior.AllowGet);
                //return View("Projects");-
            }
            else
                return new JsonResult();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="fromDate"></param>
        /// <param name="toDate"></param>
        /// <returns></returns>


        public ActionResult AddProject()
        {
            Project AddProj = new Project();


            IQueryable<Customer> tasks = this.db.Customers;
            List<SelectListItem> customers = new List<SelectListItem>();

            customers = (from dropdownfill in tasks.AsEnumerable().OrderBy(x=>x.CustomerName)
                         select new SelectListItem     // data()
                         {
                             Value = dropdownfill.CustomerName,
                             Text = dropdownfill.CustomerName
                         }).ToList();

            ViewBag.CustomerList = customers;
            IQueryable<MTS_PROJECTTYPE> projectType = this.db.MTS_PROJECTTYPE;
            List<SelectListItem> Projtype = new List<SelectListItem>();
            Projtype = (from dropdownfill in projectType.AsEnumerable().OrderBy(x=>x.Project_Type)
                        select new SelectListItem
                        {
                            Value = dropdownfill.Project_TypeID.ToString(),
                            Text = dropdownfill.Project_Type
                        }).ToList();
            ViewBag.ProjectTypeList = Projtype;
           
            IQueryable<Project> Ptasks = this.db.Projects;
            ProjectModel LastModel = new ProjectModel();

            if (Ptasks != null)
            {

                foreach (Project task in Ptasks)
                {
                    LastModel.projectcode = task.Number;
                }

            }


            AddProj.Number = (Convert.ToInt32(LastModel.projectcode) + 1).ToString();

            return PartialView("_PVAddProjects", AddProj);
        }

        [HttpPost]
        public ActionResult AddProject(Project model)
        {
            this.db.Projects.Add(model);
            this.db.SaveChanges();
            return RedirectToAction("GetProjects");
        }

        public ActionResult EditProject(int id)
        {
            IQueryable<Customer> tasks = this.db.Customers;
            List<SelectListItem> customers = new List<SelectListItem>();

            customers = (from dropdownfill in tasks.AsEnumerable().OrderBy(x=>x.CustomerName)
                         select new SelectListItem     // data()
                         {
                             Value = dropdownfill.CustomerName,
                             Text = dropdownfill.CustomerName
                         }).ToList();

            ViewBag.CustomerList = customers;
            IQueryable<MTS_PROJECTTYPE> projectType = this.db.MTS_PROJECTTYPE;
            List<SelectListItem> Projtype = new List<SelectListItem>();
            Projtype = (from dropdownfill in projectType.AsEnumerable().OrderBy(x=>x.Project_Type)
                        select new SelectListItem
                        {
                            Value = dropdownfill.Project_TypeID.ToString(),
                            Text = dropdownfill.Project_Type
                        }).ToList();
            ViewBag.ProjectTypeList = Projtype;

            Project existingTask = this.db.Projects.Find(id);

            return PartialView("_PVEditProjects", existingTask);
        }

        [HttpPost]
        public ActionResult EditProject(Project model)
        {

            Project existingproj = this.db.Projects.Where(x => x.Id.Equals(model.Id)).First();

            existingproj.Number = model.Number;
            existingproj.Name = model.Name;
            existingproj.EstStartDate = model.EstStartDate;
            existingproj.EstEndDate = model.EstEndDate;
            existingproj.Customer = model.Customer;
            existingproj.TotalAmount = model.TotalAmount;
            existingproj.Risk = model.Risk;
            existingproj.Discount = model.Discount;
            existingproj.MarginValue = model.MarginValue;
            existingproj.DiscountAmount = model.DiscountAmount;
            existingproj.Completed = model.Completed;
            existingproj.Te = model.Te;
            existingproj.Tm = model.Tm;
            existingproj.TypeOfProject = model.TypeOfProject;
            this.db.Projects.Attach(existingproj);
            db.Entry(existingproj).State = EntityState.Modified;
            this.db.SaveChanges();
            return RedirectToAction("GetProjects");
        }


        [HttpPost]
        public ActionResult DeleteProject(Int64 id)
        {
            Project existingproj = this.db.Projects.Find(id);

            this.db.Projects.Remove(existingproj);
            this.db.SaveChanges();
            return RedirectToAction("GetProjects");

        }

        #endregion


        #region Customer

        [HttpGet]
        public ActionResult GetCustomers()
        {
            return View("Customers");
        }



        public ActionResult GetCustomer(jQueryDataTableParamModel param)
        {

            IQueryable<Customer> tasks = this.db.Customers;

            if (tasks != null)
            {
                List<CustomerModel> result = new List<CustomerModel>();

                foreach (Customer task in tasks)
                {
                    CustomerModel taskModel = new CustomerModel();
                    taskModel.DT_RowId = task.CustomerId;
                    taskModel.CustomerId = task.CustomerId;
                    taskModel.CustomerName = task.CustomerName;
                    taskModel.CustomerType = task.CustomerType;
                    taskModel.CustomerAddress1 = task.CustomerAddress1;
                    taskModel.CustomerAddress2 = task.CustomerAddress2;
                    taskModel.Description = task.Description;

                    result.Add(taskModel);
                }

                var resultData = new
                {
                    aaData = result
                };
                return Json(resultData, JsonRequestBehavior.AllowGet);

            }
            else
                return new JsonResult();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="fromDate"></param>
        /// <param name="toDate"></param>
        /// <returns></returns>


        public ActionResult AddCustomer()
        {
            Customer AddCus = new Customer();
            return PartialView("_PVAddCustomer", AddCus);
        }

        [HttpPost]
        public ActionResult AddCustomer(Customer model)
        {
            this.db.Customers.Add(model);

TimeManagement/Views/Master/_PVAddConfigurations.cshtml
@model TimeManagement.Models.Configuration                
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script type="text/javascript">
    
    function isNumber(evt) {
        evt = (evt) ? evt : window.event;
        var charCode = (evt.which) ? evt.which : evt.keyCode;
        if (charCode > 31 && (charCode < 48 || charCode > 57)) {
            return false;
        }
        return true;
    }
</script>


@using (Html.BeginForm("/AddConfiguration", "Master", FormMethod.Post, new { id = "ConfigurationAddForm" }))
{    
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title">
            Add New Configuration
        </h4>
    </div>

    <div class="modal-body">
                <div class="row">
                    <div class="col-lg-12">
                      
               <div class="col-lg-12 gap-bottom5">               
                 <div class="col-lg-4 gap-top5 text-right">
                    <b>Configuration Name</b></div>
                <div class="col-lg-7">
                    @Html.TextBoxFor(m => m.Name, new { @class = "required  form-control", maxlength = "50" })
                    <div>&nbsp</div>
                    <div>@Html.ValidationMessageFor(m => m.Name)</div>
                </div>
            </div>
               <div class="col-lg-12 gap-bottom5">               
                 <div class="col-lg-4 gap-top5 text-right">
                    <b>Configuration Percentage</b></div>
                <div class="col-lg-7">
                    @Html.TextBoxFor(m => m.Percentage, new { @class = "required  form-control ", onkeypress = "return isNumber(event)" })
                    <div>&nbsp</div>
                    <div>@Html.ValidationMessageFor(m => m.Percentage)</div>
                </div>
            </div>
             <div class="col-lg-12 gap-bottom5">               
                 <div class="col-lg-4 gap-top5 text-right">
                    <b>Configuration Rate</b></div>
                <div class="col-lg-7">
                    @Html.TextBoxFor(m => m.Rate, new { @class = "required  form-control " })
                    <div>&nbsp</div>
                    <div>@Html.ValidationMessageFor(m => m.Rate)</div>
                </div>
            </div>
        </div>
         
        </div>
        

    </div>
   
    <div class="modal-footer clear">
        <button type="submit"  class="btn btn-primary">
            Add</button>
        <button type="button" data-dismiss="modal" class="btn btn-primary">
            Close</button>
          </div>
        </div>
    </div>
      
}

TimeManagement/Views/Master/_PVAddCustomer.cshtml
@model TimeManagement.Models.Customer                
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script type="text/javascript">
    $(document).ready(function () {

        $(".datePicker").datepicker();

    });
</script>
@using (Html.BeginForm("/AddCustomer", "Master", FormMethod.Post, new { id = "CustomerAddForm" }))
{    
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title">
                    Add New Customer</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-lg-12 gap-bottom5">
                        <div class="col-lg-4 gap-top5 text-right">
                            <b>Customer Name</b></div>
                        <div class="col-lg-7">
                            @Html.TextBoxFor(m => m.CustomerName, new { @class = "required form-control form-control", maxlength = "50" })
                            <div>
                                &nbsp</div>
                            <div>@Html.ValidationMessageFor(m => m.CustomerName)</div>
                        </div>
                    </div>
                    <div class="col-lg-12 gap-bottom5">
                        <div class="col-lg-4 gap-top5 text-right">
                            <b>Customer Type</b></div>
                             @{
                                    List<SelectListItem> Customertype = new List<SelectListItem>();

                                    Customertype.Add(new SelectListItem { Value = "Banking", Text = "Banking" });

                                    Customertype.Add(new SelectListItem { Value = "Commercial", Text = "Commercial" });

                                    Customertype.Add(new SelectListItem { Value = "Education", Text = "Education" });
                                    
                                    Customertype.Add(new SelectListItem { Value = "Government", Text = "Government" });

                                    Customertype.Add(new SelectListItem { Value = "HealthCare", Text = "HealthCare" });

                                    Customertype.Add(new SelectListItem { Value = "Insurance", Text = "Insurance" });

                                    Customertype.Add(new SelectListItem { Value = "Leasing", Text = "Leasing" });

                                    Customertype.Add(new SelectListItem { Value = "Mortgage", Text = "Mortgage" });

                                    ViewBag.Customertype1 = Customertype;


                                    List<SelectListItem> Customertype2 = ViewBag.Customertype1;
                                }
                        <div class="col-lg-7">
                         @*   @Html.TextBoxFor(m => m.CustomerType, new { @class = "required form-control" })*@
                          @Html.DropDownListFor(m => m.CustomerType, Customertype2, "---Select Customer Type ---", new { @class = "required form-control" })

                            <div>
                                &nbsp</div>
                            <div>@Html.ValidationMessageFor(m => m.CustomerType)</div>
                        </div>
                    </div>
                    <div class="col-lg-12 gap-bottom5">
                        <div class="col-lg-4 gap-top5 text-right">
                            <b>Customer Address1</b></div>
                        <div class="col-lg-7">
                            @Html.TextBoxFor(m => m.CustomerAddress1, new { @class = "form-control", maxlength = "200" })
                            <div>
                                &nbsp</div>
                            <div>@Html.ValidationMessageFor(m => m.CustomerAddress1)</div>
                        </div>
                    </div>
                    <div class="col-lg-12 gap-bottom5">
                        <div class="col-lg-4 gap-top5 text-right">
                            <b>Customer Address2</b></div>
                        <div class="col-lg-7">
                            @Html.TextBoxFor(m => m.CustomerAddress2, new { @class = "form-control", maxlength = "200" })
                            <div>
                                &nbsp</div>
                            <div>@Html.ValidationMessageFor(m => m.CustomerAddress2)</div>
                        </div>
                    </div>
                    <div class="col-lg-12 gap-bottom5">
                        <div class="col-lg-4 gap-top5 text-right">
                            <b>Description</b></div>
                        <div class="col-lg-7">
                            @Html.TextBoxFor(m => m.Description, new { @class = "form-control", maxlength = "200" })
                            <div>
                                &nbsp</div>
                            <div>@Html.ValidationMessageFor(m => m.Description)</div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary">
                    Add</button>
                <button type="button" data-dismiss="modal" class="btn btn-primary">
                    Close</button>
            </div>
        </div>
    </div>
}

TimeManagement/Views/Master/_PVAddLocations.cshtml
@model TimeManagement.Models.Location                
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

<script type="text/javascript">
    $(document).ready(function () {

        $(".datePicker").datepicker();

    });
</script>

@using (Html.BeginForm("/AddLocation", "Master", FormMethod.Post, new { id = "LocationAddForm" }))
{    
   <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title">
            Add New Location
        </h4>
    </div>
    <div class="modal-body">
                <div class="row">
                    <div class="col-lg-6">
                       @* <div class="col-lg-12 gap-bottom5">
                            <div class="col-lg-5 gap-top5 text-right">
                    <b>Location ID </b></div>
                <div class="col-lg-7">
                    @Html.TextBoxFor(m => m.Id, new { @class = "required form-control" })
                    <div>&nbsp</div>
                    <div>@Html.ValidationMessageFor(m => m.Id)</div>
                </div>
            </div>*@
               <div class="col-lg-12 gap-bottom5">               
                 <div class="col-lg-5 gap-top5 text-right">
                    <b>Location Name</b></div>
                <div class="col-lg-7">
                    @Html.TextBoxFor(m => m.Name, new { @class = "required form-control", maxlength = "100" })
                    <div>&nbsp</div>
                    <div>@Html.ValidationMessageFor(m => m.Name)</div>
                </div>
            </div>
        </div>
     </div>
     </div>
   
    <div class="modal-footer">
        <button type="submit"  class="btn btn-primary">
            Add</button>
        <button type="button" data-dismiss="modal" class="btn btn-primary">
            Close</button>
            </div>
           </div>
    </div>
  
}

TimeManagement/Views/Master/_PVAddWorkCodes.cshtml
@model TimeManagement.Models.WorkCode                
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script type="text/javascript">

    $(document).ready(function () {
        $("#worknum").attr("disabled", "disabled");
    });

    function isNumber(evt) {
        evt = (evt) ? evt : window.event;
        var charCode = (evt.which) ? evt.which : evt.keyCode;
        if (charCode > 31 && (charCode < 48 || charCode > 57)) {
            return false;
        }
        return true;
    }
</script>
@using (Html.BeginForm("/AddWorkCode", "Master", FormMethod.Post, new { id = "WorkCodeAddForm" }))
{    
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title">
                    Add New Work Code
                </h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="col-lg-12 gap-bottom5">
                            <div class="col-lg-4 gap-top5 text-right">
                                <b>Work Code Name</b></div>
                            <div class="col-lg-7">
                                @Html.TextBoxFor(m => m.Name, new { @class = "required  form-control", maxlength = "70" })
                                <div>
                                    &nbsp</div>
                                <div>@Html.ValidationMessageFor(m => m.Name)</div>
                            </div>
                        </div>
                        <div class="col-lg-12 gap-bottom5">
                            <div class="col-lg-4 gap-top5 text-right">
                                <b>Work Code Number</b></div>
                            <div class="col-lg-7">
                                @Html.TextBoxFor(m => m.Number, new { @class = "form-control ", onkeypress = "return isNumber(event)", id = "worknum" })
                                @Html.HiddenFor(m => m.Number)
                                <div>
                                    &nbsp</div>
                                <div>@Html.ValidationMessageFor(m => m.Number)</div>
                            </div>
                        </div>
                        <div class="col-lg-12 gap-bottom5">
                            <div class="col-lg-4 gap-top5 text-right">
                                <b>Billable</b></div>
                            <div class="col-lg-7 gap-top5">
                                @Html.CheckBoxFor(m => m.Billable)
                                <div>
                                    &nbsp</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer clear">
                <button type="submit" class="btn btn-primary">
                    Add</button>
                <button type="button" data-dismiss="modal" class="btn btn-primary">
                    Close</button>
            </div>
        </div>
    </div>
      
}